homework-07/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
import myapp.views as myapp_views
from myproject import settings

urlpatterns = [
    path('', myapp_views.PersonList.as_view()),
    path('person/create/', myapp_views.PersonCreate.as_view()),
    path('person/<int:pk>/', myapp_views.PersonDetail.as_view()),
    path('send/', myapp_views.send_mail),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

homework-07/myproject/myapp/models.py
from django.db import models

# Create your models here.


class Position(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=32)
    age = models.PositiveIntegerField(null=True)
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name='people',
        null=True
    )   # position_id

    def __str__(self):
        return self.name


class PersonProfile(models.Model):
    about_person = models.TextField()
    person = models.OneToOneField(
        Person,
        primary_key=True,
        on_delete=models.CASCADE,
    )   # person_id


class Achievement(models.Model):
    name = models.CharField(max_length=50)
    person = models.ManyToManyField(Person)

    def __str__(self):
        return self.name

homework-07/myproject/myapp/views.py
import time

from django.shortcuts import render
from django.views.generic import DetailView, ListView, CreateView
from myapp.models import Person
from . import tasks
# Create your views here.


class PageTitleMixin:
    page_title = 'The Wall of Honor'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        # print(f'{context=}')
        context['page_title'] = self.page_title

        return context


class PersonList(PageTitleMixin, ListView):
    page_title = 'People'
    model = Person
    paginate_by = 3


def send_mail(request):
    task_id = None

    print('task started', time.time())

    task = tasks.send_mail_task.delay('hello from Django', 'abcde')  # celery case
    # task = tasks.send_mail_task('hello from Django', 'abcde')  # sync case

    print('django works', time.time())

    try:
        task_id = task.id
        print('task_id', task_id)
    except Exception as e:
        pass

    context = {
        'task_id': task_id
    }
    return render(request, 'myapp/send_mail.html', context=context)


class PersonCreate(CreateView):
    model = Person
    fields = '__all__'
    success_url = '/'


class PersonDetail(PageTitleMixin, DetailView):
    model = Person

homework-07/myproject/myapp/templates/myapp/base.html
{% extends 'root.html' %}

homework-07/myproject/myapp/templates/myapp/person_detail.html
{% extends 'myapp/base.html' %}

{% block title %}
Person {{ block.super }}
{% endblock %}

{% block content %}
<h3>{{ person.name }}</h3>
<ul>
    {% for achievement in object.achievement_set.all %}
        <li>{{ achievement }}</li>
    {% endfor %}
</ul>
{% endblock %}

homework-07/myproject/myapp/templates/myapp/person_form.html
{% extends 'myapp/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create">
    </form>
{% endblock %}

homework-07/myproject/myapp/templates/myapp/person_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
    <h2>The Wall of Honor</h2>
    <h3>People ({{ object_list|length }})</h3>
    <ul>
        {% for item in object_list %}
            <li>
                {{ item.name }}, {{ item.age }} years
                ({% for achievement in item.achievement_set.all %}
                {{ achievement }}
                {% endfor %}
                )
                <p> {{item.personprofile.about_person}} </p>
            </li>
        {% endfor %}
    </ul>
    <h4>First</h4>
    <p>{{ people.0.name }}</p>
{% endblock %}myapp

homework-07/myproject/myapp/templates/myapp/send_mail.html
{% extends 'myapp/base.html' %}

{% block content %}
<h3>Task is running</h3>
{% endblock %}

homework-07/myproject/templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Myproject
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
<footer>
    {% block footer %}
        Otus, python course, 2024
    {% endblock %}
</footer>
</body>
</html>